name: HPVsim documentation
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.11' ]
    name: Build docs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.19.2'
      - name: Install HPVsim
        run:  pip install -e .
      - name: Install docs
        working-directory: ./docs
        run: pip install -r requirements.txt
      - name: Run docs build
        working-directory: ./docs
        run: ./build_docs # Build docs
